dataset:
  data_dir: '/Dataset'
  train:
    patient_ID_train: ['L067','L096','L310','L143','L192','L286','L291']
    repeat: 2
  valid:
    patient_ID_valid: ['L109']
    repeat: 3
  test:
    patient_ID_test: ['L333', 'L506']
  augment: true
  batch_size: 4
  patch_size: 128
  sampling_size:
  squeezing: true
  min_scale: 1
  max_scale: 4
  sino_unfold: true


model:
  name: cret_img
  ensembling: true
  transfer_path: '/experiment/rdn_cret_sino/model/model_best.pt'
  encoder:
    name: rdn
    upsampler: none
    input_dim: 9 #if sino_unfold: this value must be set as 9
  decoder: 
    max_freq: 5
  restorator: 
    name: swinir
    upsampler: conv
    input_dim: 1
  ct:
    view: 512
    num_split: 1
    SCD: 595 # Source-Center Distance
    SDD: 1085.6 # Souorce-Detector Distance
    num_det: 736
    det_interval: 1.2858393
    recon_interval: 0.6640625
    recon_size: [512, 512]

optimizer:
  name: ADAM
  lr: 1.e-4
  milestones: [60, 120, 180, 240]
  gamma: 0.5
  weight_decay: 0

epochs: 300
test_every: 5
save_models: false
resume: 0

n_threads: 12
cpu: false
seed: 1
